@startuml
'https://plantuml.com/sequence-diagram

autonumber
participant "processCommand:ProcessCommand" as processCommand
participant ":TimetableParser" as timetableParser
participant ":TimetableList" as timetableList
participant ":Class" as class

[-> processCommand: userCommand(command, expenseList, timetableList)
activate processCommand

processCommand -> timetableParser: parseTimetable(input)
activate timetableParser

timetableParser -> timetableList: deleteClass(details)
activate timetableList

timetableList -> timetableList: isValidDay(classDay)
activate timetableList

timetableList --> timetableList: boolean
deactivate timetableList

timetableList -> timetableList: isClassDeleted(classDay, classCode, classDeleted)
activate timetableList

loop hour in HOURS_PER_DAY
    timetableList -> class: getClassCode()
    activate class

    timetableList <-- class: classCode
    deactivate class

    alt classCode equals input classCode
        timetableList -> class !! : deleted

    end
end

timetableList --> timetableList: classDeleted
deactivate timetableList

timetableList -> timetableList: classDeletedMessage(classDeleted)
activate timetableList

timetableList --> timetableList:
deactivate timetableList

timetableList --> timetableParser
deactivate timetableList

timetableParser --> processCommand
deactivate timetableParser

processCommand -->[: false
deactivate processCommand

@enduml
