@startuml
'https://plantuml.com/sequence-diagram


autonumber
autoactivate on
participant "processCommand:ProcessCommand" as processCommand
participant ":ExpenditureList" as expenditureList
participant ":Expenditure" as expenditure

[-> processCommand: userCommand(command, expenseList, timetableList)


processCommand -> processCommand: processExpenditureUserCommand(input)


processCommand -> expenditureList: listExpenditure()

alt list is empty
    expenditureList -> expenditureList: isEmpty()
    processCommand <-- expenditureList
else list is not empty
    expenditureList -> expenditureList: size();
    loop size() times
    expenditureList -> expenditureList: get(index)
    expenditureList -> expenditure: getDescription()
    expenditureList <-- expenditure: dExpenditure description
    expenditureList -> expenditure: getType()
    expenditureList <-- expenditure: Expenditure type
    expenditureList -> expenditure: getAmount()
    expenditureList <-- expenditure: Expenditure amount
    expenditureList -> expenditure: getDate()
    expenditureList <-- expenditure: Expenditure date
    end
    processCommand <-- expenditureList: String of individual and total expenditures
end



[<-- processCommand: false


@enduml