@startuml
'https://plantuml.com/class-diagram
hide circle
skinparam classAttributeIconSize 0

package "motivationalquote" {


together {
    class MotivationalQuotes {
        # MOTIVATIONALQUOTELIST: String[]
        + getQuote(): String
    }

    class Random {
        {static} + nextInt(int bound): int
    }

    MotivationalQuotes --> Random
    }
}

    class UI {
        + printMotivationQuote(String quote)

    }

    UI --> MotivationalQuotes: getQuote()
    MotivationalQuotes "1" --> UI: Selected Quote


@enduml
