@startuml
'https://plantuml.com/sequence-diagram

autonumber
participant "processCommand:ProcessCommand" as processCommand
participant ":TimetableParser" as timetableParser
participant ":TimetableList" as timetableList
participant ":Class" as class

[-> processCommand: userCommand(command, expenseList, timetableList)
activate processCommand

processCommand -> timetableParser: parseTimetable(input)
activate timetableParser

timetableParser -> timetableList: addClass(details, true)
activate timetableList

timetableList -> timetableList: isAbleToAddClass(classTime, classDay, classDuration)
activate timetableList

timetableList -> timetableList: isValidClassTime(classTime)
activate timetableList

timetableList --> timetableList: boolean
deactivate timetableList

timetableList -> timetableList: isValidDay(classDay)
activate timetableList

timetableList --> timetableList: boolean
deactivate timetableList

timetableList -> timetableList: isSlotAvailable(classDay, classTime, classDuration)
activate timetableList

timetableList --> timetableList: boolean
deactivate timetableList

timetableList --> timetableList: boolean
deactivate timetableList

create class
timetableList -> class: new Class(classCode, classTime, classDuration, classLocation)
activate class

class --> timetableList:
deactivate class

timetableList -> timetableList: userAddedMessage(userAdded)
activate timetableList

timetableList --> timetableList:
deactivate timetableList

timetableList --> timetableParser:
deactivate timetableList

timetableParser --> processCommand:
deactivate timetableParser

processCommand -->[: false
deactivate processCommand

@enduml
