@startuml
'https://plantuml.com/sequence-diagram

autonumber
participant "processCommand:ProcessCommand" as processCommand
participant ":ExpenditureList" as expenditureList
participant ":Expenditure" as expenditure

[-> processCommand: userCommand(command, expenseList, timetableList)
activate processCommand

processCommand -> processCommand: processExpenditureUserCommand(input)
activate processCommand

processCommand -> expenditureList: addExpenditure(actionDetails, true)
activate expenditureList

expenditureList -> expenditureList: isValidDate(date)
activate expenditureList

expenditureList --> expenditureList: boolean
deactivate expenditureList

expenditureList -> expenditureList: isValidAmount(amountValue)
activate expenditureList

expenditureList --> expenditureList: boolean
deactivate expenditureList

expenditureList -> expenditureList: isValidType(type)
activate expenditureList

expenditureList --> expenditureList: boolean
deactivate expenditureList

expenditureList -> expenditureList: isValidDescription(description)
activate expenditureList

expenditureList --> expenditureList: boolean
deactivate expenditureList

create expenditure
expenditureList -> expenditure: new Expenditure(description, type, amountValue, date)
activate expenditure

expenditure --> expenditureList:
deactivate expenditure

expenditureList -> expenditureList: userAddedMessage(userAdded)
activate expenditureList

expenditureList --> expenditureList:
deactivate expenditureList

expenditureList --> processCommand:
deactivate expenditureList

processCommand --> processCommand:
deactivate processCommand

[<-- processCommand: false
deactivate processCommand

@enduml