@startuml
'https://plantuml.com/sequence-diagram

autonumber
participant "processCommand:ProcessCommand" as processCommand
participant ":ExpenditureList" as expenditureList
participant "expenditureList: ArrayList<>" as arrayList
participant ":Expenditure" as expenditure

[-> processCommand: userCommand(command, expenseList, timetableList)
activate processCommand

processCommand -> processCommand: processExpenditureUserCommand(input)
activate processCommand

processCommand -> expenditureList: deleteExpenditure(index)
activate expenditureList

expenditureList -> arrayList: get(index - 1)
activate arrayList

expenditureList <-- arrayList: expenditure
deactivate arrayList

expenditureList -> arrayList: remove((index - 1)
activate arrayList

arrayList -> expenditure !! : delete

expenditureList <-- arrayList:
deactivate arrayList

expenditureList --> processCommand:
deactivate expenditureList

processCommand --> processCommand:
deactivate processCommand

processCommand -->[: false
deactivate processCommand

@enduml
